name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - public/**
      - package.json
      - tsconfig.json
      - .github/workflows/publish.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Repository
        run: echo ${{github.repository}}

      - name: Install dependencies
        continue-on-error: true
        run:   | 
          npm config set legacy-peer-deps true
          cd ${GITHUB_WORKSPACE} && npm install
          cd ${GITHUB_WORKSPACE} && npm run build     

      - name: Change paths
        run: |
          python3 change.py          

      - name: Push changes
        run: |
          cat build/index.html

          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.email "xhrist14n@gmail.com"
          git config --global user.name "xhrist14n"

          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          ##git push origin main
        env:
          GITHUB_TOKEN:       ${{ secrets.SECRET_GITHUB_TOKEN }}
          GITHUB_REPOSITORY:  ${{github.repository}}
      
      - name: Charge to gh pages
        run: |          
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{github.repository}}
